server:
  port : 8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: product-service
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:8080
        url: http://localhost:8086
  datasource:
    url: jdbc:h2:mem:spring-security
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
            format_sql: true
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

springdoc:
  show-actuator: true