server:
  port : 8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: product-service
  security:
    user:
      name: client
      password: client
  boot:
    admin:
      client:
        username: admin
        password: admin
        instance:
          name: 'Product Admin Tool'
          management-base-url: https://service-product.onrender.com:${server.port}
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        url: https://admin-server-whpb.onrender.com:8086

  datasource:
    url: jdbc:h2:mem:spring-security
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
            format_sql: true
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

springdoc:
  show-actuator: true